- hosts: localhost

  tasks:
  - name: Execute Script
    command: python script1.py
    register:
      output
    args:
      chdir: /home/com0004/ansible-practice/python/
      
  - name: Debug of script1
    debug: msg="output is {{ output.stdout }}"
  