---
- name: runs 
  hosts: localhost

  tasks:
    - name: script1
      cammand: "python script1.py"
      register:
        output
      args:
        chdir: python/
   
    - name: Debug of script1
      debug: msg="output is {{ output.stout }}"
       
    - name: script2
      cammand: "python script2.py"
      register:
        output
      args:
        chdir: python/
        
    - name: Debug of script1
      debug: msg="output is {{ output.stout }}"
      
    - name: script3
      cammand: "python script3.py"
      register:
        output
      args:
        chdir: python/
      
    - name: Debug of script1
      debug: msg="output is {{ output.stout }}"